version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'rms'
      MYSQL_USER: 'rms'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - "3306:3306"

  app:
    image: nasanbuyan/my-spring-boot-app:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rms
      SPRING_DATASOURCE_USERNAME: rms
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
