name: Deploy Docker Image to Azure VM

on: [push]  # Triggers the workflow on every push to the repository.

jobs:
  deploy-to-azure-vm:
    runs-on: ubuntu-latest  # This job runs on an Ubuntu runner.

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: SSH and Deploy Docker Container to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            # Log in to Docker Hub if the image is private
            echo "Logging in to Docker Hub..."
            echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

            # Pull the Docker image
            echo "Pulling the Docker image..."
            docker pull nasanbuyan/rms:app

            # Stop and remove the existing container if it's already running
            if [ $(docker ps -q -f name=my-container) ]; then
              echo "Container my-container exists, stopping and removing it..."
              docker stop my-container
              docker rm my-container
            else
              echo "Container my-container does not exist, no action needed."
            fi

            # Run the new container
            echo "Running new container..."
            docker run --name my-container -d -p 80:80 nasanbuyan/rms:app
